hyeeyoung/wishboard-server

package-lock.json
package.json
src/db.js

자체 회원서비스(회원가입,로그인,로그아웃,탈퇴)를 이용하면서 bcrpty 모듈을 추가하고,
AWS에서 DB 연동을 위해 유저명을 USER -> DB_USER로 변경

[fix] bcrypt 모듈 추가

---

src/models/user.js

슬랙에서 논의한 내용을 바탕으로 nickname, profile_img 부분을 삭제하였습니다!
개발 db, 배포 db 모두 not null -> null 허용으로 변경하였습니다!

[fix] 회원가입 시 nickname, profile_img를 안받아도 되도록 변경

---

.github/workflows/ci_test.yml
package-lock.json
package.json
src/app.js
src/config/db.js
src/config/passport.js
src/config/winston.js
src/controllers/authController.js
src/controllers/cartController.js
src/controllers/folderController.js
src/controllers/itemController.js
src/models/cart.js
src/models/folder.js
src/models/item.js
src/models/user.js

log 와 관련된 winston, morgan, app-root-path 라이브러리를 추가했기 때문에 코드 내려 받은 후 npm install 해주어야 합니다. 
console.log() 사용을 지양하고 logger를 사용해주세요! 
console.log() 를 사용하는 부분을 logger로 변경하였습니다. 
sql 문 같은 경우엔 log에 기록되면 안될 것 같아서 그냥 아예 지워버렸습니다.
개발 단계에서도 확인만 console.log하고 코드는 지워버립시다 ! ! ! ! 
+ yml 파일에 dev, main 브랜치 push, pr 시 돌도록 추가했는데 커밋명을 생략해버림  > <

[add] log 추가 후 전체적으로 console.log 삭제, 관련 라이브러리 설치

---

.github/workflows/ci_test.yml
package-lock.json
package.json
src/controllers/userController.js
src/models/user.js
src/routes/userRoutes.js
webpack.config.js

CI 할 때 자꾸 clean-webpack-plugin 플러그인을 찾지 못하는 문제 발생하여 그냥 삭제했습니다. 
저 플러그인은 webpack으로 빌드한 이전 파일을 지우고 새로 설치해주는 좋은 친구인데 이상하게 자꾸 이 부분에서 에러가 발생하네요.
로컬에서는 너무 잘 동작하는데 이상합니다 .... 
저 플러그인을 지워도 로컬에서는 이전 파일 위에 덮는 것으로 보여 그냥 모듈을 삭제하였습니다. 
다시 npm install 해주시면 감사하겠습니다 > <..

User 수정 삭제 API 추가 + clean-webpack-plugin 플러그인 삭제

---

src/controllers/cartController.js
src/controllers/folderController.js
src/controllers/itemController.js
src/models/cart.js
src/models/folder.js
src/models/item.js
src/models/user.js

- 전체적으로 400 요청 추가 
- 테이블명과 칼럼명에 맞게 sql 문 수정
- `result.length == 0` 사용보다 `Array.isArray(result) && !result.length` 사용하여 가독성 신경씀!

[mod] 테이블명 및 칼럼명 통일 + insert/update/delete 시 affectedRows 사용으로 변경

---

package-lock.json
package.json
webpack.config.js

이제 이 코드를 내려받으면 전체 코드를 빌드한 파일로 돌릴 수 있습니다! 
1. `npm run build` 해서 dist 디렉터리에 build.js가 생긴 것을 확인
2. `npm start`으로 빌드파일 실행
3. log 궁금하면 /dist/logs 확인

[fix] jwt 환경변수 추가, db 환경변수명 변경

---

src/controllers/itemController.js
src/models/cart.js
src/models/item.js

회의 내용에 따라 데이터 타입을 변경하고 형변환을 추가하였습니다.
DB에도 반영하였습니다.

[mod] item_price 데이터 타입을 변경하면서 형변환 추가

---

package-lock.json
package.json

local에서 pm2를 돌릴 땐 ec2에서 발생한 문제가 확인되지 않음을 확인하였습니다.
해당 코드를 재업로드하여 npm install 후 연결테스트를 진행하도록 하겠습니다.

[fix] pm2 dependencies 추가

---

src/controllers/itemController.js
src/models/item.js
src/routes/itemRoutes.js

- 프론트 요청에 따라 홈조회 + 상세조회를 병합하였습니다.
- 테스트 도중 update/delete 부분에 유저 검증이 포함되지 않아 모르는 유저가 지울 수도 있는 보안 문제를 발견하여 검증을 추가하였습니다.
- 전체적으로 uri 와 이름을 수정하였습니다. (detail 삭제)

[mod] 홈조회 + 상세조회 병합, update/delete 시 유저 검증 추가

---

src/models/cart.js

- 프론트 요청으로 아이템 상세조회 항목과 아이템 카운트 값을 return 하는 형식으로 쿼리 변경
- 보내주는 값을 wishItem과 cartItemCount로 나눠서 전송
- 코드 리팩토링은 바로 진행할 예정 (우선 코드 테스트를 위해 먼저 업로드)

[mod] cart select 시 요청 retun 값 변경

---

src/dto/cartResponse.js
src/models/cart.js

- 프론트가 요청한 형태로 return 하기 위해 converter 함수로 따로 빼두어 가독성 확보
- 쿼리 결과의 return 형태가 배열안에 객체 형태이기 때문에 for문을 통한 접근이 필수적
- 최대한 가독성을 확보하려고 노력함

[refator] cart 조회 리팩토링

---

.gitignore
src/controllers/notiController.js
src/models/noti.js
src/routes/notiRoutes.js
src/utils/response.js
src/utils/strings.js

1. `.gitignore` : FCM key 파일 추가
2.  `firebase-admin` 모듈 추가 : Firebase FCM 서비스 사용을 위함. 코드 내려받고 **npm install** 해주세요!
3. 알림 기능 구현 
- 알림 생성 : FCM 서버에 **알림 전송 성공 여부**에 따라 DB에 알림 정보 **insert** 함(주의 깊게 살펴봐주셔요..!)
- 알림 조회
- 알림 정보 업데이트
- 알림 read_state 업데이트 : **unread(0)** 상태의 알림을 **read(1)** 상태로 업데이트
- 알림 삭제
4. `Response.js` 에 알림 관련  **response string** 추가
5. `strings.js` 추가 : FCM 서버에 전송할 알림 메세지의 **title, description string** 값을 해당 파일로 분리함. 
- 서버에 전송할 데이터 관련 string값을 작성할 때 해당 파일에 정리하면 좋을 것 같습니다!
6. 수정 필요 : 현재 DB **notification** 테이블에서 **item_notification_type**, **item_notification_date** 필드 null 값 허용 -> **not null** 제약조건 추가 필요
- 위의 수정사항이 반영될 것을 고려하여 알림 생성 및 알림 정보 업데이트 시  **item_id** + **item_notification_type**, **item_notification_date**가 존재하지 않을 경우 **BadRequest** 예외를 던지도록 함

[feat] 알림 기능 구현

---

src/dto/cartResponse.js
src/models/cart.js

[fix] 카트조회 시 cart_item_id -> cart_state로 변경하고 true/false 값으로 전달

---

src/controllers/cartController.js
src/models/cart.js

n개 처리 -> 1개 처리를 다수 요청으로 변경하면서 쿼리를 변경하고 예외처리를 추가하였습니다.

[mod] 수정 요청 방식 변경으로 쿼리 변경

---

.eslintrc.json
.prettierrc.js
package-lock.json
package.json

- ESLint 라고 하는 소스코드 단위 정적 분석 도구를 이용하여 문법 규칙, compiler error 를 잡음
- runtime error나 메모리 누수 같은 에러는 소스코드 단위로 파악 불가. 빌드 정적 분석 진행해야 함. (이 부분도 추후에 구현 예정 ........)
- Prettier를 사용하여 ESLint로는 잡지 못하는 코드 포맷팅을 진행
- package.json에서 사용하지 않는 의존 파일 삭제
- `cors`, `@mapbox/node-pre-gyp` 사용 안함
-  `cardinal` mysql2에 helper 안에 있는 필요 파일 같은데 없어도 동작 가능
- `pm2`는 앱에 대한 의존 파일이기 보다는 개발 시 필요한 파일이라 생각되어 devDependencies로 위치 옮김
---
주석은 이해를 위해 추가하였고, 코멘트 남긴거 확인한 후 삭제, commit --amend 하여 반영할 예정입니다!

[feat] ESLint, Prettier 파일 추가 및 사용하지 않는 dependencies 삭제

---

src/models/cart.js

회의 내용에 따라 cart 수정 사항 반영
1. 테이블에 create_at 필드를 추가하고 조회 시 정렬을 최신순으로 변경
- sqlSelect 부분의 쿼리가 변경되었습니다! (하단 order by 쪽에 `c.create_at`)
2. 현재 ESLint 적용으로 인해 저장과 동시 리포맷 됨
- vscode 설정을 저장 시 리포맷 되도록 변경해두었더니 리포맷 되었습니다.
- var를 사용 지양 규칙 적용
- reassigned 되는 경우엔 let을 사용하고, 아닌 경우엔 const 를 쓰도록 하였습니다.! 
- 이로 인해 전체적으로 저장하면서 조금 변경되었음을 알려드립니다! 
- `selectCart` 부분에 쿼리 끝만 봐주시면 됩니다!

[mod] 카트 create_at 필드 추가 및 조회 시 최신순으로 정렬

---

src/controllers/authController.js
src/controllers/userController.js
src/middleware/auth.js
src/middleware/handleError.js
src/models/user.js
src/routes/authRoutes.js
src/routes/userRoutes.js

401 예외 반환 시 보내주는 메세지 형태를 변경하고 코드 리포맷을 진행
1. 예외 반환 메세지 수정
[기존]
```json
{
"success": false,
"message": "token이 유효하지 않음"
}
```
[현재]
```json
{
"success": false,
"message": "token 없음. 요청 token 확인"
}
```
2. 코드 리포맷
- var -> const로 변경
- "" -> ''로 변경

[mod] 사용자 401 예외 메세지 수정 + 코드 리포맷

---

src/controllers/itemController.js
src/models/item.js
src/routes/itemRoutes.js
src/utils/response.js

1. insert 시 
- `itemController.js` : item_img not null 제약조건 해제 후 예외처리에서 삭제 -> item_name으로 수정
- `item.js` : item_img, item_price null값이 올 경우 0 또는 null로 들어가게 수정 
2. update, delete 시 
- `itemRoutes.js` : item_id를 path로 받도록 수정
- `item.js` :  item_id를 param으로 받도록 수정, update 요청 시 item_img, item_price null값이 올 경우 0 또는 null로 들어가게 수정 
3. 코드 리포맷
- var -> const로 변경
- "" -> ''로 변경
- `item.js`에서 insert 부분과 update 부분에 item_img, item_price, item_name 위주로 봐주세요!

[mod] 아이템 등록, 수정, 삭제 수정 + 코드 리포맷

---

src/controllers/authController.js
src/controllers/cartController.js
src/controllers/userController.js
src/dto/cartResponse.js
src/middleware/auth.js
src/middleware/handleError.js
src/models/cart.js
src/models/item.js
src/models/user.js
src/routes/authRoutes.js
src/routes/cartRoutes.js
src/routes/userRoutes.js

item_price null로 들어가는 문제 해결
1. item_price null 검사 후 null 인경우 0이 들어가도록 수정
2. 추가로 select * 시 return 되는 결과 값을 변경
- 기존에는 return value인 rows, 즉 `RowDataPacket[]` 형태가 return 됐습니다.
- 도메인을 직접 return 하는 것은 보안상 좋지 않기 때문에 `return Object.setPrototypeOf(rows, []);`하여 새로운 배열에 rows 데이터를 넣도록 하여 쿼리 그자체가 아닌 새 객체 배열로 반환 되도록 수정하였습니다. (다른 곳 model에도 적용할 예정)
- 죄송...합니다... 뭔가 꼬이면서 merge 커밋이 함께 올라가서 12개 파일이 올라갔네요... `item.js`만 확인해주세요

[fix] item_price null 저장 문제 해결

---

src/controllers/cartController.js
src/dto/cartResponse.js
src/models/cart.js
src/routes/cartRoutes.js

API 문서를 수정하면서 uri 에 item_id를 추가
1. 수정, 삭제에 대한 기능 요청 시 uri 에 item_id 추가
- item_id가 uri에 추가되면서 해당 path parameter를 빼는 경우에는 다음과 같은 에러가 발생합니다.
```json
{
"success": false,
"message": "API URL is invalid"
}
```
- item_id를 params로 받는 것으로 수정하면서 수정, 삭제 시 BadRequest 예외처리에서 삭제하였습니다.
2. `CartResponse.js` parameter camelCase로 변경
- 기본 camelCase 작성을 원칙으로 하였기 때문에 property는 카멜케이스로 합니다. 
- 프론트 측과 논의 후에 보낼 때는 snake_case를 유지하기로 했기 때문에 this 로 받을 때는 형태 유지합니다. (주석 참고)
- 리팩토링 필요한 부분 (좋은 의견 받습니다..)
- `itemRoutes.js`에 :item_id가 update, delete 시 추가된 것 확인 부탁
- `cartController.js`에 :item_id가 update, delete 시 추가된 것 확인 부탁
- `cart.js`에 `const itemId = req.params.item_id`로 받는지 확인 부탁
- insert 시에는 해당 아이템을 삭제한다거나 수정하는게 아니니까 item_id를 포함하지 않았는데 포함하는게 맞는지도 고려 부탁

[mod] 장바구니 update, delete api 수정 + 코드 리포맷

---

src/dto/cartResponse.js
src/models/cart.js

피드백 주신 내용을 바탕으로 cartResponse 내용을 수정하였습니다. 
- CartItem 클래스 생성하여 wishItem, cartItemInfo를 담도록 수정

[mod] 장바구니 cartResponse 리팩토링

---

src/controllers/itemController.js
src/controllers/notiController.js
src/models/item.js
src/utils/strings.js

item 수정 시 쿼리를 수정하고, 함수명을 변경하였습니다. 
`!req.body.item_img` 이런 식으로 할 경우, null을 담아 보낼 때 값이 있는 거로 확인하는 문제가 발생하여 `undefined`로 조건 걸어두었습니다.
코드가 맘에 들지 않아 추후 변경될 예정입니다.

[fix] item update 시 쿼리 수정 + [mod] update, delete 함수명 변경

---

src/controllers/notiController.js
src/models/item.js
src/utils/strings.js

true 문자열 형변환
String에 true를 지우고 true(booelan 타입)의 문자열이 필요한 경우 toString() 함수를 이용하도록 변경
- `[fix] item update 시 쿼리 수정` 이 커밋을 noti 후에 커밋하여 이렇게 같이 들어가게 되었습니다 .. 양해바랍니다 😢

[mod] true 문자열 형변환으로 변경

---

src/controllers/folderController.js
src/models/folder.js
src/routes/folderRoutes.js
src/utils/response.js

img보다 thumbnail로 하는 것이 보기 쉽고, 명확하게 파악하기 좋아서 folder_img -> folder_thumbnail로 수정합니다.
1. TODO 주석 삭제
2. `folderContorller.js`, `folder.js`, `folderRoutesr.js` 에서 folder_img를 사용하던 부분을 folder_thumbnail로 수정
3. db 필드명 수정

[mod] folder_img -> folder_thumbnail 수정

---

.gitignore
src/app.js
src/config/winston.js

logger와 .gitignore 추가
1. logger 예외 출력를 출력하도록 코드 추가
2. logger 기본 문자열 포맷 development 시 dev로 변경
3. vscode에서 settings.json 파일 안올라가도록 수정

logger development일 때 출력 형식 변경

---

src/models/folder.js

폴더 조회, 폴더 리스트 조회 시 썸네일을 이상하게 가져오는 문제 해결
SelectFolder, SelectFolderList 중 썸네일 부분에 해당하는 쿼리 변경
버그 리포트는 여기에 상세히 적어두었으니 궁금하시면 보세요! (#73)

[fix] 폴더 조회, 폴더 리스트 조회 쿼리 변경

---

src/controllers/folderController.js
src/models/folder.js
src/routes/folderRoutes.js
src/utils/response.js

1. 폴더 삭제 시 유저 검증 부분이 빠져있어 추가
2. 폴더 추가/수정 시 폴더명 유효성 검증 추가
`folderController.js`에서 폴더명 추가/수정 전 후로 유효성 검증을 수행하여 `isVaildate`가 false인 경우에만 추가/수정 하도록 변경하였습니다.

폴더명 유효성 검증 추가 + 폴더 삭제 시 유저 검증 추가

---

src/controllers/authController.js
src/models/folder.js
src/utils/errors.js
src/utils/response.js

이미 존재하는지 검사하는 부분에 대해서는 Conflict 로 수정하였습니다.
1. `authController.js`에서는 아이디가 존재할 경우, BadRequest -> Conflict로 수정
2. `folder.js`에서는 폴더명이 존재할 경우, BadRequest -> Conflict로 수정
3. Conflict 클래스 추가

[mod] Conflict status code 추가

---

package-lock.json
package.json
src/app.js
src/config/db.js
src/controllers/notiController.js
src/middleware/notiScheduler.js
src/models/noti.js
src/routes/notiRoutes.js
src/utils/notiPushMessage.js
src/utils/response.js
src/utils/strings.js

- node-scheduler 모듈을 이용하여 배치 작업을 추가
- 마이페이지에서 알림 여부 토글에 따라 api를 요청(`/noti/schedule?push=true/false`)
- 정기적으로 스케줄러를 이용하여 쿼리를 요청 -> 결과 값에 있는 경우, firebase fcm server에 알림을 보내 스케줄 알림처럼 구현
- 마이페이지에서 알림 여부 토글에 따라 요청을 보내는 api는(`/noti/schedule?push=true/false`) query string 형태입니다. 주의!
몇 가지 논의하고 싶은 부분이 있습니다.
1. 5분 전이라고 스케줄 알림을 보내야 할 데이터가 있는지 확인하는 쿼리 요청을 얼마 간격으로 실행시킬지
-  `notiController.js` - scheduleSettings()
- 현재 매 분마다(매분 00초에 스케줄러 실행) 쿼리 요청하여 값이 존재하는 경우 fcm server로 전송
- **몇 분 간격으로 하는게 좋을지 고민** 되는 부분
2. **쿼리 중 선택하거나 더 좋은 쿼리 ...를 고안해야 할 필요**가 있음 (주석 부분)
- `noti.js` -  selectNotiFrom5minAgo() // 주석 참고
- 현재 돌아가는 쿼리는 `WHERE n.item_notification_date >= (now() - INTERVAL 5 MINUTE)` `>=`로 해두어서 5분 후 ~ 이후 모든 알림으로 쿼리 결과 반환 (테스트를 위해서 다음과 같이 우선 해둠)
- 주석 처리 해둔 거보다 더 좋은 방법이나 혜안이 있다면 받습니다.
3. 안드 쪽에서 Strings로 …

[feat] 유저별 스케줄 알림 구현

---

.github/workflows/serverCI.yml

기존 파일에 deploy 부분을 추가합니다.
기존에 ec2에서 production 모드로 빌드를 하지 못하는 문제가 발생하여 git action 에서 빌드하여 s3 버킷으로 올리는 작업을 진행합니다. 
현재 추가되지 않은 가장 아래 주석은 이후에 pm2 실행 명령어를 추가할 예정입니다.
현재 flow는 다음과 같습니다.
```
ci 진행 -> 브랜치에 따라 빌드 진행 -> 빌드 파일을 s3에 업로드 -> ec2에 원격접속하여 s3 업로드 파일 다운로드
```
1. action 실행 부 이름을 대문자로 시작하도록 변경하였습니다.
2. deploy 부분이 추가되었습니다.

[feat] cicd yaml 파일에 deploy 부분을 추가

---

src/config/passport.js
src/controllers/authController.js
src/models/user.js

회의 내용에 따라 회원가입 및 로그인 성공 시 response에 `push_state` 값을 삭제합니다. 
사용자 정보 조회  시, `fcm_token` 값은 필요 없는 것으로 확인되어 해당 부분도 삭제합니다.

[chore] 회원가입 및 로그인 시 push_state 전달 삭제

---

src/models/item.js
src/models/user.js

아요 작업 중 이슈 확인되어 멀티파트 api 수정/삭제 시 예외처리 추가합니다. 
1. 멀티파트 api 수정/삭제 시 예외처리 추가

멀티파트 api 수정/삭제 시 예외처리 추가

---

src/models/noti.js

아요 작업 중 알림 조회 시 아이템 이미지가 보이지 않는 이슈를 확인하여 해당 부분을 수정합니다.
1. 알림 조회 시 아이템 이미지 url 보이도록 수정

알림 조회 시 아이템 이미지 url 보이도록 수정

---

src/controllers/itemController.js
src/models/item.js
src/routes/itemRoutes.js

- closed #212 
1. 아이템 상세조회 api 구현

[feat] 아이템 상세조회 api 구현

---

src/middleware/rateLimiter.js

1초에 최대 20번 요청 가능하도록 수정합니다. 
1. rateLimiter.js 파일의 max 매개변수 값 조정

[fix] 1초에 최대 20번 요청 가능하도록 수정

---

src/models/folder.js
src/models/item.js
src/models/user.js
src/utils/util.js

문자열 앞 뒤 공백 제거하는 함수 구현했습니다. 
1. 문자열 앞 뒤 공백 제거하는 함수 구현
2. 아이템 상품명, 아이템 메모, 폴더명, 닉네임에 대하여 반영

[feat] 문자열 앞 뒤 공백 제거하는 함수 구현

---

src/models/item.js
src/models/user.js
src/utils/util.js

유저 탈퇴 시 s3 에 사진 삭제 코드 추가 및 전반적으로 에러 핸들링 변경
1. 유저 탈퇴 시 s3 에 사진 삭제 코드 추가 및 전반적으로 에러 핸들링 변경
2 문자열 trim util에 타입 확인 if문 추가

유저 탈퇴 시 s3 에 사진 삭제 코드 추가 및 전반적으로 에러 핸들링 변경

---

src/models/item.js
src/models/user.js
src/utils/S3ImageUtils.js

s3에서 이미지 삭제하는 로직 모듈화
1. s3에서 이미지를 삭제하는 반복 코드를 모듈화하였습니다.

s3에서 이미지 삭제하는 로직 모듈화

---

src/models/cart.js
src/models/folder.js
src/models/item.js
src/models/noti.js

클라 요청에 따라 UI로 보이는 텍스트들 중 null인 경우 ""로 변경했습니다.
1. UI로 보이는 텍스트들 중 null인 경우 ""로 변경

[mod] UI로 보이는 텍스트들 중 null인 경우 ""로 변경

---

src/app.js
src/controllers/itemController.js
src/models/item.js

- close #231 
1. [hotfix] 아이템 추가 시 folder 지정 안해도 등록 되도록 수정
2. 사용하지 않는 import 삭제 (app.js)
3. await 문 추가

Dev hotfix item insert

---

src/config/passport.js
src/controllers/authController.js
src/models/user.js

- close #240 
1. 임시 닉네임 로그인 처리 시 이미 닉네임이 있는 경우에는 null 보내도록 예외처리 추가

[mod] 임시 닉네임 로그인 처리 시 이미 닉네임이 있는 경우에는 null 보내도록 예외처리 추가

---

src/controllers/authController.js

response nickname -> tempNickname 으로 수정
- 로그인, 재로그인 시 response nickname -> tempNickname 으로 수정

[fix] response nickname -> tempNickname 으로 수정

---

src/controllers/userController.js
src/models/user.js

[mod] 비밀번호 api 수정

---

src/controllers/authController.js
src/lib/parser.js
src/utils/jwtUtils.js

[add] 서울스토어 가격 파싱 추가

---

src/controllers/authController.js
src/models/user.js

재로그인 시 fcmToken 받도록 추가
1. 재로그인 시 fcmToken 받도록 추가

[mod] 재로그인 시 fcmToken 받도록 추가

---

.github/workflows/developDeploy.yml
.github/workflows/prCheck.yml
.github/workflows/productDeploy.yml
src/config/redis.js
webpack.config.js
webpack.prod.config.js

redis 패스워드 설정 추가
redis 패스워드 설정 추가

[mod] redis 패스워드 설정 추가

---

infra/README.md
infra/ansible.cfg
infra/inventory
infra/server-ubuntu-setup.yaml

[chore] 서버 세팅 관련 ansible 스크립트 추가

---

src/controllers/versionController.js
src/models/version.js
src/routes/index.js
src/routes/versionRoutes.js
src/utils/response.js

release 1.3.5
